apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleet
resources:
  - namespace.yaml
  - postgres.yaml
  - clickhouse.yaml
  - apiserver.yaml
  - gateway.yaml
  - operator.yaml
