// Package devstub is an in-process stand-in for an inference engine.
//
// It exists so that the gateway, the console and the integration tests can be
// exercised without a GPU. It is a development aid, never linked into a
// production path: nothing outside a test or an explicit --demo flag
// constructs one.
package devstub

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"
)

// Config shapes the stub's observable behaviour.
type Config struct {
	// Models is what /v1/models advertises. The first is the default.
	Models []string
	// TokenDelay is the pause between streamed deltas. Zero returns the whole
	// answer in one frame, which hides every streaming bug.
	TokenDelay time.Duration
	// PromptTokens is the reported prompt count. Fixed, because a stub that
	// invents a different number on each call makes a metering assertion
	// untestable.
	PromptTokens int
	// Reply overrides the default answer text.
	Reply string
	// Silent answers without a usage object at all.
	//
	// It exists because "the engine reports nothing" is a shape the gateway
	// has to survive and a stub that always reports usage can never produce.
	// With it on, the gateway counts the answer itself and bills that, which is
	// the path no amount of testing the happy path would reach.
	Silent bool
}

func (c *Config) withDefaults() Config {
	out := *c
	if len(out.Models) == 0 {
		out.Models = []string{"demo/Qwen2.5-1.5B-Instruct"}
	}
	if out.PromptTokens <= 0 {
		out.PromptTokens = 412
	}
	if out.Reply == "" {
		out.Reply = defaultReply
	}
	return out
}

const defaultReply = "This answer is generated by Fleet's built-in stub engine, not by a " +
	"model. Use it to exercise the console: streaming, usage accounting and " +
	"endpoint routing all behave as they will against vLLM or llama.cpp, but the " +
	"words are canned. Point the gateway at a real engine and this text goes away."

// Engine is a running stub. Close stops it.
type Engine struct {
	cfg     Config
	http    *http.Server
	baseURL string
}

// Start listens on 127.0.0.1 at an OS-assigned port and returns the engine and
// the base URL to configure as an upstream.
func Start(cfg Config) (*Engine, string, error) {
	cfg = cfg.withDefaults()

	ln, err := listenLocal()
	if err != nil {
		return nil, "", err
	}

	e := &Engine{cfg: cfg, baseURL: "http://" + ln.Addr().String()}
	e.http = &http.Server{Handler: e.routes(), ReadHeaderTimeout: 5 * time.Second}
	go func() { _ = e.http.Serve(ln) }()
	return e, e.baseURL, nil
}

func (e *Engine) Close() {
	if e.http == nil {
		return
	}
	_ = e.http.Close()
}

func (e *Engine) models(w http.ResponseWriter, r *http.Request) {
	now := time.Now().Unix()
	list := map[string]any{"object": "list", "data": []any{}}
	for _, m := range e.cfg.Models {
		list["data"] = append(list["data"].([]any), map[string]any{
			"id": m, "object": "model", "created": now, "owned_by": "devstub",
		})
	}
	writeJSON(w, http.StatusOK, list)
}

func (e *Engine) chat(w http.ResponseWriter, r *http.Request) {
	req, err := decodeRequest(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid_request_error", err.Error())
		return
	}
	if !e.serves(req.Model) {
		writeError(w, http.StatusNotFound, "invalid_request_error",
			fmt.Sprintf("the stub engine does not serve %q", req.Model))
		return
	}

	if !req.Stream {
		e.writeCompletion(w, req)
		return
	}
	e.writeStream(w, r, req)
}

type chatRequest struct {
	Model         string `json:"model"`
	Stream        bool   `json:"stream"`
	StreamOptions *struct {
		IncludeUsage bool `json:"include_usage"`
	} `json:"stream_options"`
	MaxTokens int `json:"max_tokens"`
}

func (e *Engine) serves(model string) bool {
	for _, m := range e.cfg.Models {
		if m == model {
			return true
		}
	}
	return false
}

func (e *Engine) writeCompletion(w http.ResponseWriter, req chatRequest) {
	completion := len(strings.Fields(e.cfg.Reply))
	out := map[string]any{
		"id": "chatcmpl-devstub", "object": "chat.completion",
		"model": req.Model, "created": time.Now().Unix(),
		"choices": []any{map[string]any{
			"index":         0,
			"message":       map[string]any{"role": "assistant", "content": e.cfg.Reply},
			"finish_reason": "stop",
		}},
	}
	if !e.cfg.Silent {
		out["usage"] = e.usage(completion)
	}
	writeJSON(w, http.StatusOK, out)
}

func (e *Engine) usage(completion int) map[string]any {
	return map[string]any{
		"prompt_tokens":     e.cfg.PromptTokens,
		"completion_tokens": completion,
		"total_tokens":      e.cfg.PromptTokens + completion,
	}
}

func withChoice(base map[string]any, delta map[string]any, finishReason any) map[string]any {
	out := make(map[string]any, len(base)+1)
	for k, v := range base {
		out[k] = v
	}
	out["choices"] = []any{map[string]any{
		"index": 0, "delta": delta, "finish_reason": finishReason,
	}}
	return out
}

func decodeRequest(r *http.Request) (chatRequest, error) {
	var req chatRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		return req, fmt.Errorf("body is not a chat completion request")
	}
	if req.Model == "" {
		return req, fmt.Errorf("model is required")
	}
	return req, nil
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func writeError(w http.ResponseWriter, status int, kind, msg string) {
	writeJSON(w, status, map[string]any{
		"error": map[string]any{"message": msg, "type": kind, "code": kind},
	})
}

func writeText(w http.ResponseWriter, status int, body string) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(status)
	_, _ = w.Write([]byte(body))
}
