// Command fleet-gateway is the OpenAI-compatible entry point: routing, metering
// and the operator console, in one binary with no Kubernetes dependency (P7).
package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/zlogic-labs/fleet/core/internal/devstub"
	"github.com/zlogic-labs/fleet/core/internal/gateway"
	"github.com/zlogic-labs/fleet/core/pkg/entitlement"
)

// version is overridden at build time with -ldflags "-X main.version=...".
var version = "dev"

type options struct {
	configPath  string
	listen      string
	logLevel    string
	edition     string
	showVer     bool
	demo        bool
	demoNoUsage bool
}

func parseFlags() options {
	var o options
	flag.StringVar(&o.configPath, "config", os.Getenv("FLEET_CONFIG"),
		"path to a YAML config file")
	flag.StringVar(&o.listen, "listen", "",
		"override the listen address")
	flag.StringVar(&o.logLevel, "log-level", "info",
		"debug, info, warn or error")
	flag.StringVar(&o.edition, "edition", "",
		"override the edition: community or enterprise")
	flag.BoolVar(&o.showVer, "version", false,
		"print the version and exit")
	flag.BoolVar(&o.demo, "demo", false,
		"serve a built-in stub engine, for trying the console without a GPU")
	flag.BoolVar(&o.demoNoUsage, "demo-no-usage", false,
		"with --demo, answer without a usage object so the gateway counts the answer itself")
	flag.Parse()
	return o
}

func main() {
	opts := parseFlags()

	if opts.showVer {
		fmt.Println("fleet-gateway", version)
		return
	}

	log := newLogger(opts.logLevel)

	cfg, err := gateway.Load(opts.configPath)
	if err != nil {
		log.Error("invalid configuration", "error", err)
		os.Exit(1)
	}
	if opts.listen != "" {
		cfg.Listen = opts.listen
	}
	if opts.edition != "" {
		cfg.Edition = opts.edition
	}

	if opts.demo {
		stub, err := addStub(&cfg, log, opts.demoNoUsage)
		if err != nil {
			log.Error("could not start the demo engine", "error", err)
			os.Exit(1)
		}
		defer stub.Close()
	}

	log.Info("starting",
		"version", version,
		"listen", cfg.Listen,
		"upstreams", len(cfg.Upstreams),
		"config", opts.configPath)

	ctx := waitForShutdown()
	if err := gateway.Run(ctx, cfg, licenseFor(cfg.Edition), log, version); err != nil {
		log.Error("gateway stopped", "error", err)
		os.Exit(1)
	}
}

// addStub appends a built-in engine so the gateway has something to serve.
// An operator who already declared upstreams keeps them; the stub is an
// addition, not a replacement, so --demo is safe on a real config file.
func addStub(cfg *gateway.Config, log *slog.Logger, silent bool) (*devstub.Engine, error) {
	stub, baseURL, err := devstub.Start(devstub.Config{Silent: silent})
	if err != nil {
		return nil, err
	}
	// Explicit upstreams win, so a demo run against a configured deployment
	// does not silently reroute traffic onto canned answers.
	if len(cfg.Upstreams) == 0 {
		cfg.Upstreams = append(cfg.Upstreams, gateway.UpstreamConfig{
			ID:                  "devstub",
			Model:               "demo/Qwen2.5-1.5B-Instruct",
			BaseURL:             baseURL,
			Engine:              "devstub",
			Replicas:            1,
			AffinityPrefixRunes: 512,
		})
		log.Warn("demo engine in use: replies are canned, not generated by a model",
			"engine_url", baseURL, "model", cfg.Upstreams[0].Model)
	} else {
		log.Warn("demo engine started but not registered: upstreams are already configured",
			"engine_url", baseURL)
	}
	return stub, nil
}

// licenseFor resolves the edition from configuration.
//
// A single-node gateway has no control plane to ask for a licence, so the
// answer comes from configuration here. The enterprise build replaces this
// function with one that reads a signed licence file; the seam is
// entitlement.License, so nothing downstream changes.
func licenseFor(edition string) entitlement.License {
	if edition == string(entitlement.EditionEnterprise) {
		return entitlement.Enterprise("", time.Time{})
	}
	return entitlement.Community()
}

// waitForShutdown blocks until an interrupt or termination arrives, then
// returns a context that the run loop watches.
func waitForShutdown() context.Context {
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-ctx.Done()
		stop()
	}()
	return ctx
}

func newLogger(level string) *slog.Logger {
	var lv slog.Level
	switch level {
	case "debug":
		lv = slog.LevelDebug
	case "warn":
		lv = slog.LevelWarn
	case "error":
		lv = slog.LevelError
	default:
		lv = slog.LevelInfo
	}
	return slog.New(slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{Level: lv}))
}
